name: Deploy pages
on:
    push:
        branches:
          - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: prepare
              run: |
                mkdir -p build
                touch build/.nojekyll
            - name: pandoc
              uses: docker://pandoc/core:latest-alpine
              with:
                args: >-
                  --standalone 
                  --embed-resources
                  --css=tufte.css
                  --css=cici.css
                  --output=build/index.html
                  --metadata title="Tai Chi Chuan & Chi Kung for Fitness"
                  README.md
            - name: deploy
              uses: JamesIves/github-pages-deploy-action@4.1.0
              with:
                branch: gh-pages
                folder: build
